language: node_js
node_js:
  - "8"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - project/node_modules
    - project/client/node_modules
install:
  - cd project
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 3
  - npm run test